# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='date_returned',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='time_returned',
            field=models.TimeField(null=True),
        ),
    ]
