# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory to /app
WORKDIR ./

# Copy the current directory contents into the container at /lab_inventory
ADD . /lab_inventory

# Install any needed packages specified in requirements.txt
RUN pip install
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python manage.py runserver"]
